/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IDFC_Project;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class TrackingOrder extends javax.swing.JPanel {

    private double counter = 0;
    private double increase = 33.33;
    
    public TrackingOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();

        setMinimumSize(new java.awt.Dimension(1200, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 103, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Processing.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(90, 90));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 90));
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 90));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Packaging.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/In_Transit.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 80, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delivered.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 220, 80, 80));

        bar.setForeground(new java.awt.Color(102, 255, 0));
        add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 1100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        fill(counter + increase);
    }//GEN-LAST:event_btnAddActionPerformed
    
    public void fill(double total) {
        while(counter <= total) {
            bar.setValue((int)counter);
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
            counter += 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
